### ISSUE TITLE
fix misspelling in rbokeh docs

### ISSUE THREAD

**Issue by timelyportfolio** [hafen/hafen.github.io#1]
I think this is autobuilt, so I'm not sure how to fix with a pull, but on the bokeh documentation.

![image](https://cloud.githubusercontent.com/assets/837910/6155538/ba4af9b0-b1f9-11e4-9a11-8925393dcf8c.png)

**Comment by hafen** [comment]
Thanks.  Fixed.  I have pushed up the .Rmd files.  Building requires a package I haven't pushed up yet, but feel free to PR edits to the index.Rmd.  rd.Rmd is auto-generated.
